// /**
//  * Halo API Documentation
//  * Documentation for Halo API
//  *
//  * OpenAPI spec version: unknown
//  * Contact: hi@halo.run
//  *
//  * NOTE: This class is auto generated by the swagger code generator program.
//  * https://github.com/swagger-api/swagger-codegen.git
//  * Do not edit the class manually.
//  */
// /* tslint:disable:no-unused-variable member-ordering */

// import { Inject, Injectable, Optional }                      from '@angular/core';
// import { HttpClient, HttpHeaders, HttpParams,
//          HttpResponse, HttpEvent }                           from '@angular/common/http';
// import { CustomHttpUrlEncodingCodec }                        from '../encoder';

// import { Observable }                                        from 'rxjs/Observable';

// import { BaseResponseobject } from '../model/baseResponseobject';
// import { OptionDTO } from '../model/optionDTO';

// import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
// import { Configuration }                                     from '../configuration';


// @Injectable()
// export class OptionControllerService {

//     protected basePath = 'https://127.0.0.1:8090';
//     public defaultHeaders = new HttpHeaders();
//     public configuration = new Configuration();

//     constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
//         if (basePath) {
//             this.basePath = basePath;
//         }
//         if (configuration) {
//             this.configuration = configuration;
//             this.basePath = basePath || configuration.basePath || this.basePath;
//         }
//     }

//     /**
//      * @param consumes string[] mime-types
//      * @return true: consumes contains 'multipart/form-data', false: otherwise
//      */
//     private canConsumeForm(consumes: string[]): boolean {
//         const form = 'multipart/form-data';
//         for (const consume of consumes) {
//             if (form === consume) {
//                 return true;
//             }
//         }
//         return false;
//     }


//     /**
//      * Options for comment
//      * 
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public commentUsingGET(observe?: 'body', reportProgress?: boolean): Observable<any>;
//     public commentUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
//     public commentUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
//     public commentUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

//         let headers = this.defaultHeaders;

//         // authentication (Access key from header) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["API-Authorization"]) {
//             headers = headers.set('API-Authorization', this.configuration.apiKeys["API-Authorization"]);
//         }

//         // authentication (Access key from query) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["api_access_key"]) {
//             queryParameters = queryParameters.set('api_access_key', this.configuration.apiKeys["api_access_key"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//         ];

//         return this.httpClient.get<any>(`${this.basePath}/api/content/options/comment`,
//             {
//                 params: queryParameters,
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * Gets option value by option key
//      * 
//      * @param key key
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public getByUsingGET13(key: string, observe?: 'body', reportProgress?: boolean): Observable<BaseResponseobject>;
//     public getByUsingGET13(key: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BaseResponseobject>>;
//     public getByUsingGET13(key: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BaseResponseobject>>;
//     public getByUsingGET13(key: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         if (key === null || key === undefined) {
//             throw new Error('Required parameter key was null or undefined when calling getByUsingGET13.');
//         }

//         let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

//         let headers = this.defaultHeaders;

//         // authentication (Access key from header) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["API-Authorization"]) {
//             headers = headers.set('API-Authorization', this.configuration.apiKeys["API-Authorization"]);
//         }

//         // authentication (Access key from query) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["api_access_key"]) {
//             queryParameters = queryParameters.set('api_access_key', this.configuration.apiKeys["api_access_key"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//         ];

//         return this.httpClient.get<BaseResponseobject>(`${this.basePath}/api/content/options/keys/${encodeURIComponent(String(key))}`,
//             {
//                 params: queryParameters,
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * Lists all options with list view
//      * 
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public listAllUsingGET5(observe?: 'body', reportProgress?: boolean): Observable<Array<OptionDTO>>;
//     public listAllUsingGET5(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<OptionDTO>>>;
//     public listAllUsingGET5(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<OptionDTO>>>;
//     public listAllUsingGET5(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

//         let headers = this.defaultHeaders;

//         // authentication (Access key from header) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["API-Authorization"]) {
//             headers = headers.set('API-Authorization', this.configuration.apiKeys["API-Authorization"]);
//         }

//         // authentication (Access key from query) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["api_access_key"]) {
//             queryParameters = queryParameters.set('api_access_key', this.configuration.apiKeys["api_access_key"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//         ];

//         return this.httpClient.get<Array<OptionDTO>>(`${this.basePath}/api/content/options/list_view`,
//             {
//                 params: queryParameters,
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * Lists options with map view
//      * 
//      * @param key key
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public listAllWithMapViewUsingGET1(key?: Array<string>, observe?: 'body', reportProgress?: boolean): Observable<any>;
//     public listAllWithMapViewUsingGET1(key?: Array<string>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
//     public listAllWithMapViewUsingGET1(key?: Array<string>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
//     public listAllWithMapViewUsingGET1(key?: Array<string>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


//         let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
//         if (key) {
//             key.forEach((element) => {
//                 queryParameters = queryParameters.append('key', <any>element);
//             })
//         }

//         let headers = this.defaultHeaders;

//         // authentication (Access key from header) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["API-Authorization"]) {
//             headers = headers.set('API-Authorization', this.configuration.apiKeys["API-Authorization"]);
//         }

//         // authentication (Access key from query) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["api_access_key"]) {
//             queryParameters = queryParameters.set('api_access_key', this.configuration.apiKeys["api_access_key"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//         ];

//         return this.httpClient.get<any>(`${this.basePath}/api/content/options/map_view`,
//             {
//                 params: queryParameters,
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

// }
