// /**
//  * Halo API Documentation
//  * Documentation for Halo API
//  *
//  * OpenAPI spec version: unknown
//  * Contact: hi@halo.run
//  *
//  * NOTE: This class is auto generated by the swagger code generator program.
//  * https://github.com/swagger-api/swagger-codegen.git
//  * Do not edit the class manually.
//  */
// /* tslint:disable:no-unused-variable member-ordering */

// import { Inject, Injectable, Optional }                      from '@angular/core';
// import { HttpClient, HttpHeaders, HttpParams,
//          HttpResponse, HttpEvent }                           from '@angular/common/http';
// import { CustomHttpUrlEncodingCodec }                        from '../encoder';

// import { Observable }                                        from 'rxjs/Observable';

// import { PagePhotoDTO } from '../model/pagePhotoDTO';
// import { PhotoDTO } from '../model/photoDTO';

// import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
// import { Configuration }                                     from '../configuration';


// @Injectable()
// export class PhotoControllerService {

//     protected basePath = 'https://127.0.0.1:8090';
//     public defaultHeaders = new HttpHeaders();
//     public configuration = new Configuration();

//     constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
//         if (basePath) {
//             this.basePath = basePath;
//         }
//         if (configuration) {
//             this.configuration = configuration;
//             this.basePath = basePath || configuration.basePath || this.basePath;
//         }
//     }

//     /**
//      * @param consumes string[] mime-types
//      * @return true: consumes contains 'multipart/form-data', false: otherwise
//      */
//     private canConsumeForm(consumes: string[]): boolean {
//         const form = 'multipart/form-data';
//         for (const consume of consumes) {
//             if (form === consume) {
//                 return true;
//             }
//         }
//         return false;
//     }


//     /**
//      * listPhotos
//      * 
//      * @param sort 
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public listPhotosUsingGET1(sort?: Array<string>, observe?: 'body', reportProgress?: boolean): Observable<Array<PhotoDTO>>;
//     public listPhotosUsingGET1(sort?: Array<string>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PhotoDTO>>>;
//     public listPhotosUsingGET1(sort?: Array<string>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PhotoDTO>>>;
//     public listPhotosUsingGET1(sort?: Array<string>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


//         let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
//         if (sort) {
//             sort.forEach((element) => {
//                 queryParameters = queryParameters.append('sort', <any>element);
//             })
//         }

//         let headers = this.defaultHeaders;

//         // authentication (Access key from header) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["API-Authorization"]) {
//             headers = headers.set('API-Authorization', this.configuration.apiKeys["API-Authorization"]);
//         }

//         // authentication (Access key from query) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["api_access_key"]) {
//             queryParameters = queryParameters.set('api_access_key', this.configuration.apiKeys["api_access_key"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//         ];

//         return this.httpClient.get<Array<PhotoDTO>>(`${this.basePath}/api/content/photos/latest`,
//             {
//                 params: queryParameters,
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * pageBy
//      * 
//      * @param keyword 
//      * @param page 
//      * @param size 
//      * @param sort 
//      * @param team 
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public pageByUsingGET10(keyword?: string, page?: number, size?: number, sort?: Array<string>, team?: string, observe?: 'body', reportProgress?: boolean): Observable<PagePhotoDTO>;
//     public pageByUsingGET10(keyword?: string, page?: number, size?: number, sort?: Array<string>, team?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PagePhotoDTO>>;
//     public pageByUsingGET10(keyword?: string, page?: number, size?: number, sort?: Array<string>, team?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PagePhotoDTO>>;
//     public pageByUsingGET10(keyword?: string, page?: number, size?: number, sort?: Array<string>, team?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






//         let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
//         if (keyword !== undefined && keyword !== null) {
//             queryParameters = queryParameters.set('keyword', <any>keyword);
//         }
//         if (page !== undefined && page !== null) {
//             queryParameters = queryParameters.set('page', <any>page);
//         }
//         if (size !== undefined && size !== null) {
//             queryParameters = queryParameters.set('size', <any>size);
//         }
//         if (sort) {
//             sort.forEach((element) => {
//                 queryParameters = queryParameters.append('sort', <any>element);
//             })
//         }
//         if (team !== undefined && team !== null) {
//             queryParameters = queryParameters.set('team', <any>team);
//         }

//         let headers = this.defaultHeaders;

//         // authentication (Access key from header) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["API-Authorization"]) {
//             headers = headers.set('API-Authorization', this.configuration.apiKeys["API-Authorization"]);
//         }

//         // authentication (Access key from query) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["api_access_key"]) {
//             queryParameters = queryParameters.set('api_access_key', this.configuration.apiKeys["api_access_key"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//         ];

//         return this.httpClient.get<PagePhotoDTO>(`${this.basePath}/api/content/photos`,
//             {
//                 params: queryParameters,
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

// }
