/**
 * Halo API Documentation
 * Documentation for Halo API
 *
 * OpenAPI spec version: unknown
 * Contact: hi@halo.run
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostListVO } from './postListVO';


export interface ArchiveMonthVO { 
    month?: number;
    posts?: Array<PostListVO>;
    year?: number;
}
