/**
 * Halo API Documentation
 * Documentation for Halo API
 *
 * OpenAPI spec version: unknown
 * Contact: hi@halo.run
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface JournalWithCmtCountDTO { 
    commentCount?: number;
    content?: string;
    createTime?: Date;
    id?: number;
    likes?: number;
    sourceContent?: string;
    type?: JournalWithCmtCountDTO.TypeEnum;
}
export namespace JournalWithCmtCountDTO {
    export type TypeEnum = 'INTIMATE' | 'PUBLIC';
    export const TypeEnum = {
        INTIMATE: 'INTIMATE' as TypeEnum,
        PUBLIC: 'PUBLIC' as TypeEnum
    };
}
