/**
 * Halo API Documentation
 * Documentation for Halo API
 *
 * OpenAPI spec version: unknown
 * Contact: hi@halo.run
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MenuVO { 
    children?: Array<MenuVO>;
    icon?: string;
    id?: number;
    name?: string;
    parentId?: number;
    priority?: number;
    target?: string;
    team?: string;
    url?: string;
}
