/**
 * Halo API Documentation
 * Documentation for Halo API
 *
 * OpenAPI spec version: unknown
 * Contact: hi@halo.run
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PhotoDTO { 
    description?: string;
    id?: number;
    location?: string;
    name?: string;
    takeTime?: Date;
    team?: string;
    thumbnail?: string;
    url?: string;
}
