/**
 * Halo API Documentation
 * Documentation for Halo API
 *
 * OpenAPI spec version: unknown
 * Contact: hi@halo.run
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseMetaDTO } from './baseMetaDTO';


export interface SheetDetailVO { 
    commentCount?: number;
    createTime?: Date;
    disallowComment?: boolean;
    editTime?: Date;
    editorType?: SheetDetailVO.EditorTypeEnum;
    formatContent?: string;
    fullPath?: string;
    id?: number;
    likes?: number;
    metaDescription?: string;
    metaIds?: Array<number>;
    metaKeywords?: string;
    metas?: Array<BaseMetaDTO>;
    originalContent?: string;
    password?: string;
    slug?: string;
    status?: SheetDetailVO.StatusEnum;
    summary?: string;
    template?: string;
    thumbnail?: string;
    title?: string;
    topPriority?: number;
    topped?: boolean;
    updateTime?: Date;
    visits?: number;
    wordCount?: number;
}
export namespace SheetDetailVO {
    export type EditorTypeEnum = 'MARKDOWN' | 'RICHTEXT';
    export const EditorTypeEnum = {
        MARKDOWN: 'MARKDOWN' as EditorTypeEnum,
        RICHTEXT: 'RICHTEXT' as EditorTypeEnum
    };
    export type StatusEnum = 'DRAFT' | 'INTIMATE' | 'PUBLISHED' | 'RECYCLE';
    export const StatusEnum = {
        DRAFT: 'DRAFT' as StatusEnum,
        INTIMATE: 'INTIMATE' as StatusEnum,
        PUBLISHED: 'PUBLISHED' as StatusEnum,
        RECYCLE: 'RECYCLE' as StatusEnum
    };
}
