/**
 * Halo API Documentation
 * Documentation for Halo API
 *
 * OpenAPI spec version: unknown
 * Contact: hi@halo.run
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserDTO } from './userDTO';


export interface StatisticWithUserDTO { 
    attachmentCount?: number;
    birthday?: number;
    categoryCount?: number;
    commentCount?: number;
    establishDays?: number;
    journalCount?: number;
    likeCount?: number;
    linkCount?: number;
    postCount?: number;
    tagCount?: number;
    user?: UserDTO;
    visitCount?: number;
}
