/**
 * Halo API Documentation
 * Documentation for Halo API
 *
 * OpenAPI spec version: unknown
 * Contact: hi@halo.run
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Author } from './author';


export interface ThemeProperty { 
    activated?: boolean;
    author?: Author;
    branch?: string;
    description?: string;
    folderName?: string;
    hasOptions?: boolean;
    id?: string;
    logo?: string;
    name?: string;
    postMetaField?: Array<string>;
    repo?: string;
    require?: string;
    screenshots?: string;
    sheetMetaField?: Array<string>;
    themePath?: string;
    version?: string;
    website?: string;
}
