/**
 * Halo API Documentation
 * Documentation for Halo API
 *
 * OpenAPI spec version: unknown
 * Contact: hi@halo.run
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserDTO { 
    avatar?: string;
    createTime?: Date;
    description?: string;
    email?: string;
    id?: number;
    mfaType?: UserDTO.MfaTypeEnum;
    nickname?: string;
    updateTime?: Date;
    username?: string;
}
export namespace UserDTO {
    export type MfaTypeEnum = 'NONE' | 'TFA_TOTP';
    export const MfaTypeEnum = {
        NONE: 'NONE' as MfaTypeEnum,
        TFATOTP: 'TFA_TOTP' as MfaTypeEnum
    };
}
